@echo off
forfiles /p c:\users\ /s /m *.dma /c "cmd /c echo  @path" > Violations.txt
forfiles /p c:\users\ /s /m *.mp3 /c "cmd /c echo  @path" >> Violations.txt
forfiles /p c:\users\ /s /m *.docx /c "cmd /c echo  @path" >> Violations.txt
forfiles /p c:\users\ /s /m *.mp4 /c "cmd /c echo  @path" >> Violations.txt
forfiles /p c:\users\ /s /m *.asf  /c "cmd /c echo  @path" >> Violations.txt
forfiles /p c:\users\ /s /m *.ogg  /c "cmd /c echo  @path" >> Violations.txt
forfiles /p c:\users\ /s /m *.wma  /c "cmd /c echo  @path" >> Violations.txt
forfiles /p c:\users\ /s /m *.wmv  /c "cmd /c echo  @path" >> Violations.txt
forfiles /p c:\users\ /s /m *.wm  /c "cmd /c echo  @path" >> Violations.txt
forfiles /p c:\users\ /s /m *.asx  /c "cmd /c echo  @path" >> Violations.txt
forfiles /p c:\users\ /s /m *.wax  /c "cmd /c echo  @path" >> Violations.txt
forfiles /p c:\users\ /s /m *.wvx  /c "cmd /c echo  @path" >> Violations.txt
forfiles /p c:\users\ /s /m *.wmx  /c "cmd /c echo  @path" >> Violations.txt
forfiles /p c:\users\ /s /m *.dvr-ms  /c "cmd /c echo  @path" >> Violations.txt
forfiles /p c:\users\ /s /m *.wmd  /c "cmd /c echo  @path" >> Violations.txt
forfiles /p c:\users\ /s /m *.avi  /c "cmd /c echo  @path" >> Violations.txt
forfiles /p c:\users\ /s /m *.mpg  /c "cmd /c echo  @path" >> Violations.txt
forfiles /p c:\users\ /s /m *.mpeg  /c "cmd /c echo  @path" >> Violations.txt
forfiles /p c:\users\ /s /m *.m1v  /c "cmd /c echo  @path" >> Violations.txt
forfiles /p c:\users\ /s /m *.mp2  /c "cmd /c echo  @path" >> Violations.txt
forfiles /p c:\users\ /s /m *.mpa  /c "cmd /c echo  @path" >> Violations.txt
forfiles /p c:\users\ /s /m *.mpe  /c "cmd /c echo  @path" >> Violations.txt
forfiles /p c:\users\ /s /m *.m3u  /c "cmd /c echo  @path" >> Violations.txt
forfiles /p c:\users\ /s /m *.mid  /c "cmd /c echo  @path" >> Violations.txt
forfiles /p c:\users\ /s /m *.midi  /c "cmd /c echo  @path" >> Violations.txt
forfiles /p c:\users\ /s /m *.rmi  /c "cmd /c echo  @path" >> Violations.txt
forfiles /p c:\users\ /s /m *.aif  /c "cmd /c echo  @path" >> Violations.txt
forfiles /p c:\users\ /s /m *.aifc  /c "cmd /c echo  @path" >> Violations.txt
forfiles /p c:\users\ /s /m *.aiff  /c "cmd /c echo  @path" >> Violations.txt
forfiles /p c:\users\ /s /m *.au  /c "cmd /c echo  @path" >> Violations.txt
forfiles /p c:\users\ /s /m *.snd  /c "cmd /c echo  @path" >> Violations.txt
forfiles /p c:\users\ /s /m *.wav  /c "cmd /c echo  @path" >> Violations.txt
forfiles /p c:\users\ /s /m *.cda  /c "cmd /c echo  @path" >> Violations.txt
forfiles /p c:\users\ /s /m *.ivf  /c "cmd /c echo  @path" >> Violations.txt
forfiles /p c:\users\ /s /m *.wmz  /c "cmd /c echo  @path" >> Violations.txt
forfiles /p c:\users\ /s /m *.wms  /c "cmd /c echo  @path" >> Violations.txt
forfiles /p c:\users\ /s /m *.mov  /c "cmd /c echo  @path" >> Violations.txt
forfiles /p c:\users\ /s /m *.m4a  /c "cmd /c echo  @path" >> Violations.txt
forfiles /p c:\users\ /s /m *.m4v  /c "cmd /c echo  @path" >> Violations.txt
forfiles /p c:\users\ /s /m *.mp4v  /c "cmd /c echo  @path" >> Violations.txt
forfiles /p c:\users\ /s /m *.3g2  /c "cmd /c echo  @path" >> Violations.txt
forfiles /p c:\users\ /s /m *.3gp2  /c "cmd /c echo  @path" >> Violations.txt
forfiles /p c:\users\ /s /m *.3gp  /c "cmd /c echo  @path" >> Violations.txt
forfiles /p c:\users\ /s /m *.3gpp  /c "cmd /c echo  @path" >> Violations.txt
forfiles /p c:\users\ /s /m *.aac  /c "cmd /c echo  @path" >> Violations.txt
forfiles /p c:\users\ /s /m *.adt  /c "cmd /c echo  @path" >> Violations.txt
forfiles /p c:\users\ /s /m *.adts  /c "cmd /c echo  @path" >> Violations.txt
forfiles /p c:\users\ /s /m *.m2ts /c "cmd /c echo  @path" >> Violations.txt
forfiles /p c:\users\ /s /m *.jpg /c "cmd /c echo  @path" >> Violations.txt
forfiles /p c:\users\ /s /m *.raw /c "cmd /c echo  @path" >> Violations.txt
forfiles /p c:\users\ /s /m *.jpeg /c "cmd /c echo  @path" >> Violations.txt
forfiles /p c:\users\ /s /m *.hdp /c "cmd /c echo  @path" >> Violations.txt
forfiles /p c:\users\ /s /m *.wdp /c "cmd /c echo  @path" >> Violations.txt
forfiles /p c:\users\ /s /m *.gif /c "cmd /c echo  @path" >> Violations.txt
forfiles /p c:\users\ /s /m *.png /c "cmd /c echo  @path" >> Violations.txt
start Violations.txt
exit